name: Build Android APK

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-android-apk:
    name: Build Android APK
    runs-on: windows-latest
    timeout-minutes: 90
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install .NET workloads
        run: dotnet workload install android

      - name: Restore
        run: dotnet restore osu.Android.slnf

      - name: Build Release
        run: dotnet build -c Release osu.Android.slnf --no-restore

      - name: Build AAB
        run: |
          dotnet publish osu.Android/osu.Android.csproj -c Release -p:AndroidKeyStore=false -p:AndroidPackageFormat=aab -o ./artifacts

      - name: Build APK
        run: |
          dotnet publish osu.Android/osu.Android.csproj -c Release -p:AndroidKeyStore=false -p:AndroidPackageFormat=apk -o ./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ./artifacts/*.apk
          retention-days: 30

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: ./artifacts/*.aab
          retention-days: 30